### ISSUE TITLE
Import component from dynamic path

### ISSUE THREAD

**Issue by oskareke** [hector-del-rio/gatsby-plugin-loadable-components-ssr#6] opened 2020-08-26 15:03 UTC
Is it possible to import a component from a dynamic path? 

This works:
`const Component = loadable(() => import("./component.js"))
`

Where as this doesn't:
```
const modulePath = "./component.js"
const Component = loadable(() => import(modulePath))
```

The error I get is:
`/loadable.js: Property value expected type of string but got null`

I'm guessing webpack doesn't manage to figure this out, but are there any known workaround for this?

Great plugin 👍

**Comment by MaxBoltik** [comment] 2020-08-30 10:30
the same problem

**Comment by theKashey** [comment] 2020-09-05 03:15
@oskareke - this is not how it works. Please refer to [require.context](https://webpack.js.org/guides/dependency-management/#requirecontext) API. It shall be a __simple__ template based mask(that's important!), or just a static string. Anything else - and it will blow up.
```js
⛔️ const modulePath = "./component.js"
⛔️ const Component = loadable(() => import(modulePath))

✅ const modulePath = "./component.js"
✅ const Component = loadable(({someVariable}) => import('/somepath/${someVariable}`));
✅ <Component someVariable={modulePath} />
```

---
Came around from the same problem - https://github.com/gregberge/loadable-components/issues/621
I am not sure how Gatsby manages SSR, but by the time it tried to render the page - modules referenced via  full dynamic import are not preset in the module cache.

Loadable expects all chunks to be "synchronously available" and usually achieves it via separate SSR configuration, with splitting disabled (basically [target="node"](https://webpack.js.org/configuration/target/#target)).
I've tried to apply the same changes via `onCreateWebpackConfig` but not sure they had any effect.

```
import(() => `components/${name}`)
```
- `'./src/component weak recursive ^\\.\\/.*$'` is present in the cache.
- `'./src/component/AnyComponent'` is __not__, leading to `Cannot read property 'call' of undefined`

**Comment by graysonhicks** [comment] 2021-05-10 21:35
I believe, ultimately, this is a duplicate of #4 .

**Closed by graysonhicks** 2021-05-10 21:35 UTC
